# Site settings
title: LISFESTUDIO
email: Lisfe.Studio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  LISFESTUDIO有著許多關於前端技術與資料呈現的筆記與分享，
  也包含了一些實驗性的新想法
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lisfe.github.io" # the base hostname & protocol for your site
# twitter_username: lisfe
github_username:  lisfe

# Build settings
markdown: kramdown
highlighter: rouge